nombre = input("Ingresar su nombre: ")
apellido = input("Ingresar su apellido: ")
rut = input("Ingresar su RUT: ")
duoc_mail = input("Ingresar su correo electrónico Duoc: ") 
duoc_sede = input("Ingresar su sede Duoc: ")
print("Datos ingresados: ") 
print("Nombre:", nombre)
print("Apellido:", apellido) 
print("Rut:", rut)
print("Duoc_mail:", duoc_mail) 
print("Duoc_sede:", duoc_sede)
